config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/admin' => 'admin#index', as: :admin_index

  devise_for :users, :controllers => {:registrations => "registrations"}

  get '/admin/pays' => 'countries#index_admin', as: :country_admin_index
  get '/admin/pays/new' => 'countries#new', as: :country_new
  post '/admin/pays/create' => 'countries#create', as: :country_create
  patch '/admin/pays/update/:id' => 'countries#update', as: :country_update
  get '/admin/pays/edit/:id' => 'countries#edit', as: :country_edit
  delete '/admin/pays/delete/:id' => 'countries#destroy', as: :country_delete

  get '/admin/utilisateurs' => 'admin#users_index', as: :users_admin_index
  get '/admin/utilisateurs/download' => 'admin#users_download', as: :users_download

  get '/admin/matches' => 'match#index_admin', as: :match_admin
  get '/admin/match/new' => 'match#new', as: :match_new
  get '/matchs/' => 'match#index', as: :match
  post '/admin/match/create' => 'match#create', as: :match_create
  delete '/admin/match/delete/:id' => 'match#destroy', as: :match_delete
  get '/admin/match/edit/:id' => 'match#edit', as: :match_edit
  put '/admin/match/update/:id' => 'match#update', as: :match_update

  get '/admin/pools' => 'pool#index_admin', as: :pools_admin
  get '/admin/pool/new' => 'pool#new', as: :pool_new
  post '/admin/pool/create' => 'pool#create', as: :pool_create
  delete '/admin/pool/delete/:id' => 'pool#destroy', as: :pool_delete
  get '/admin/pool/edit/:id' => 'pool#edit', as: :pool_edit
  put '/admin/pool/update/:id' => 'pool#update', as: :pool_update

  get '/results' => 'results#resultats'

  get '/admin/stades' => 'stade#index_admin', as: :stade_admin
  get '/admin/stade/new' => 'stade#new', as: :stade_new
  post 'admin/stade/create' => 'stade#create', as: :stade_create
  delete '/admin/stade/delete/:id' => 'stade#destroy', as: :stade_delete
  get '/admin/stade/edit/:id' => 'stade#edit', as: :stade_edit
  put '/admin/stade/update/:id' => 'stade#update', as: :stade_update

  get '/admin/prizes' => 'prizes#index_admin', as: :prize_admin_index
  get '/admin/prizes/new' => 'prizes#new', as: :prize_new
  get '/prizes/' => 'prizes#index', as: :prize
  post '/admin/prizes/create' => 'prizes#create', as: :prize_create
  patch '/admin/prizes/update/:id' => 'prizes#update', as: :prize_update
  get '/admin/prizes/edit/:id' => 'prizes#edit', as: :prize_edit
  delete '/admin/prizes/delete/:id' => 'prizes#destroy', as: :prize_delete

  get '/legales/sitemap' => 'legales#sitemap', as: :sitemap
  get '/legales/reglement' => 'legales#rules', as: :rules

end

app/models/pool.rb
class Pool < ActiveRecord::Base
  validates :name, length: { minimum: 1, maximum: 64 }

  has_many :matches
end

app/controllers/pool_controller.rb
class PoolController < ApplicationController
  layout 'admin', except: [:index]
  before_action :admin_require, except: [:index]

  def index_admin
    @pools = Pool.order(name: :asc)
  end

  def index

  end

  def new

  end

  def edit
    @pool = Pool.find_by(id: params[:id])
  end

  def create
    @pool = Pool.new(pool_params)

    if @pool.valid?
      @pool.save

      redirect_to :pools_admin
      return
    end

    render 'new'
  end

  def update
    @pool = Pool.find_by(id: params[:id])

    if @pool.update(pool_params)
      redirect_to :pools_admin
    else
      render 'edit'
    end
  end

  def destroy
    @pool = Pool.find(params[:id])
    @pool.destroy

    redirect_to :pools_admin
  end

  private
  def pool_params
    params.require(:pool).permit(:name)
  end
end

app/helpers/pool_helper.rb
module PoolHelper
  def pool_errors_messages!
    return "" unless pool_errors_messages?

    messages = @pool.errors.messages.map { |msg| content_tag(:li, msg[1][0])}.join

    html = <<-HTML
      <div class="error">
        <ul>#{messages}</ul>
      </div>
    HTML

    html.html_safe
  end

  def pool_errors_messages?
    !@pool.nil?
  end
end

app/views/pool/edit.html.erb
<% content_for :header do %>
    <h2>Modifier <%= @pool.name %></h2>
<% end %>

<div class="col-xs-6">
  <div class="box box-primary">

    <%= pool_errors_messages! %>

    <%= form_for :pool, url: pools_update_path, method: :put do |f| %>
        <div class="box-body">
          <div class="form-group">
            <label>Nom : </label>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>

        <div class="box-footer">
          <%= f.submit value: 'Engresitrer les modifications', class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>

app/views/pool/index_admin.html.erb
<% content_for 'header' do %>
    <h2>Listes des poules</h2>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Poules</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
            <div class="row">
              <div class="col-sm-6"></div>
              <div class="col-sm-6"></div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                  <col width="auto">
                  <col width="100px">
                  <thead>
                  <tr role="row">
                    <th class="sorting" tabindex="0" rowspan="1" colspan="1">Nom</th>
                    <th rowspan="1" colspan="1">Actions</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @pools.each do |pool| %>
                      <tr role="row" class="odd">
                        <td><%= pool.name %></td>
                        <td>
                          <%= link_to pool_edit_path(pool), data: {no_turbolink: true} do %>
                            <span class="glyphicon glyphicon-edit"></span>
                          <% end %>
                          <%= link_to pool_delete_path(pool), method: :delete, data: { confirm: 'Êtes vous sûr?' } do %>
                            <span class="glyphicon glyphicon-remove-circle red" aria-hidden="true"></span>
                          <% end %>
                        </td>
                      </tr>
                  <% end %>
                  </tbody>
                  <tfoot>
                  <tr>
                    <th rowspan="1" colspan="1">Nom</th>
                    <th rowspan="1" colspan="1">Actions</th>
                  </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    </div><!-- /.col -->
  </div><!-- /.row -->

  <%= link_to 'Ajouter une poule', pool_new_path, class: 'btn btn-primary' %>
</section>

app/views/pool/new.html.erb
<% content_for :header do %>
    <h2>Ajouter une poule</h2>
<% end %>

<div class="col-xs-6">
  <div class="box box-primary">

    <%= pool_errors_messages! %>

    <%= form_for :pool, url: pool_create_path do |f| %>
        <div class="box-body">
          <div class="form-group">
            <label>Nom : </label>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>

        <div class="box-footer">
          <%= f.submit value: 'Enregistrer', class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>