config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/admin' => 'admin#index', as: :admin_index

  devise_for :users, :controllers => {:registrations => "registrations"}

  get '/admin/pays' => 'countries#index_admin', as: :country_admin_index
  get '/admin/pays/new' => 'countries#new', as: :country_new
  post '/admin/pays/create' => 'countries#create', as: :country_create
  patch '/admin/pays/update/:id' => 'countries#update', as: :country_update
  get '/admin/pays/edit/:id' => 'countries#edit', as: :country_edit
  delete '/admin/pays/delete/:id' => 'countries#destroy', as: :country_delete

  get '/admin/utilisateurs' => 'admin#users_index', as: :users_admin_index
  get '/admin/utilisateurs/download' => 'admin#users_download', as: :users_download

  get '/admin/matches' => 'match#index_admin', as: :match_admin
  get '/admin/match/new' => 'match#new', as: :match_new
  get '/matchs/' => 'match#index', as: :match
  post '/admin/match/create' => 'match#create', as: :match_create
  delete '/admin/match/delete/:id' => 'match#destroy', as: :match_delete
  get '/admin/match/edit/:id' => 'match#edit', as: :match_edit
  put '/admin/match/update/:id' => 'match#update', as: :match_update

  get '/admin/pools' => 'pool#index_admin', as: :pools_admin
  get '/admin/pool/new' => 'pool#new', as: :pool_new
  post '/admin/pool/create' => 'pool#create', as: :pool_create
  delete '/admin/pool/delete/:id' => 'pool#destroy', as: :pool_delete
  get '/admin/pool/edit/:id' => 'pool#edit', as: :pool_edit
  put '/admin/pool/update/:id' => 'pool#update', as: :pool_update

  get '/results' => 'results#resultats'

  get '/admin/stades' => 'stade#index_admin', as: :stade_admin
  get '/admin/stade/new' => 'stade#new', as: :stade_new
  post 'admin/stade/create' => 'stade#create', as: :stade_create
  delete '/admin/stade/delete/:id' => 'stade#destroy', as: :stade_delete
  get '/admin/stade/edit/:id' => 'stade#edit', as: :stade_edit
  put '/admin/stade/update/:id' => 'stade#update', as: :stade_update

  get '/admin/prizes' => 'prizes#index_admin', as: :prize_admin_index
  get '/admin/prizes/new' => 'prizes#new', as: :prize_new
  get '/prizes/' => 'prizes#index', as: :prize
  post '/admin/prizes/create' => 'prizes#create', as: :prize_create
  patch '/admin/prizes/update/:id' => 'prizes#update', as: :prize_update
  get '/admin/prizes/edit/:id' => 'prizes#edit', as: :prize_edit
  delete '/admin/prizes/delete/:id' => 'prizes#destroy', as: :prize_delete

  get '/legales/sitemap' => 'legales#sitemap', as: :sitemap
  get '/legales/reglement' => 'legales#rules', as: :rules

end

app/models/stade.rb
class Stade < ActiveRecord::Base
  validates :name, length: { minimum: 3, maximum: 100 }, allow_nil: false, presence: true

  has_many :matches
end

app/controllers/stade_controller.rb
class StadeController < ApplicationController
  before_action :admin_require
  layout 'admin'

  def index_admin
    @stades = Stade.order(:name => :asc)
  end

  def new

  end

  def create
    @stade = Stade.new(stade_params)

    if @stade.valid?
      @stade.save
      redirect_to :stade_admin
    else
      render 'new'
    end
  end

  def edit
    @stade = Stade.find_by(:id => params[:id])
  end

  def update
    @stade = Stade.find_by(:id => params[:id])

    if @stade.update(stade_params)
      redirect_to :stade_admin
    else
      render 'edit'
    end
  end

  def destroy
    @stade = Stade.find_by(:id => params[:id])
    @stade.destroy

    redirect_to :stade_admin
  end

  private
  def stade_params
    params.require(:stade).permit(:name, :address)
  end
end

app/helpers/stade_helper.rb
module StadeHelper
end

app/views/stade/edit.html.erb
<% content_for :header do %>
    <h2>Modifier <%= @stade.name %></h2>
<% end %>

<div class="col-xs-6">
  <div class="box box-primary">
    <%= form_for :stade, url: stade_update_path, method: :put do |f| %>
        <div class="box-body">
          <div class="form-group">
            <label>Nom : </label><br />
            <%= f.text_field :name, class: 'form-control', placeholder: 'Entrez le nom du stade' %>
            <label>Adresse : </label><br />
            <%= f.text_field :address, class: 'form-control', placeholder: 'Entrez l\'adresse du stade' %>
          </div>
        </div>

        <div class="box-footer">
          <%= f.submit value: 'Engresitrer les modifications', class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>

app/views/stade/index_admin.html.erb
<% content_for 'header' do %>
    <h2>Listes des stades</h2>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Hover Data Table</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
            <div class="row">
              <div class="col-sm-6"></div>
              <div class="col-sm-6"></div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                  <col width="auto">
                  <col width="100px">
                  <thead>
                  <tr role="row">
                    <th class="sorting" tabindex="0" rowspan="1" colspan="1">Nom du stade</th>
                    <th class="middle-row" rowspan="1" colspan="1">Adresse</th>
                    <th class="actions" rowspan="1" colspan="1">Actions</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @stades.each do |stade| %>
                      <tr role="row" class="odd">
                        <td><%= stade.name %></td>
                        <td><%= stade.address %></td>
                        <td>
                          <%= link_to stade_edit_path(stade), data: {no_turbolink: true} do %>
                              <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                          <% end %>

                          <%= link_to stade_delete_path(stade), method: :delete, data: { confirm: 'Êtes vous sûr?' } do %>
                              <span class="glyphicon glyphicon-remove-circle red" aria-hidden="true"></span>
                          <% end %>
                        </td>
                      </tr>
                  <% end %>
                  </tbody>
                  <tfoot>
                  <tr>
                    <th rowspan="1" colspan="1">Nom du stade</th>
                    <th class="middle-row" rowspan="1" colspan="1">Adresse</th>
                    <th class="actions" rowspan="1" colspan="1">Actions</th>
                  </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    </div><!-- /.col -->
  </div><!-- /.row -->

  <%= link_to 'Ajouter un stade', stade_new_path, class: 'btn btn-primary' %>
</section>

app/views/stade/new.html.erb
<% content_for :header do %>
    <h2>Ajouter un stade</h2>
<% end %>

<div class="col-xs-6">
  <div class="box box-primary">
    <%= match_errors_messages! %>

    <%= form_for :stade, url: stade_create_path do |f| %>
        <div class="box-body">
          <div class="box-body">
            <div class="form-group">
              <label>Nom : </label><br />
              <%= f.text_field :name, class: 'form-control', placeholder: 'Entrez le nom du stade' %>
              <label>Adresse : </label><br />
              <%= f.text_field :address, class: 'form-control', placeholder: 'Entrez l\'adresse du stade' %>
            </div>
          </div>
        </div>

        <div class="box-footer">
          <%= f.submit value: 'Enregistrer', class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>