config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/admin' => 'admin#index', as: :admin_index

  devise_for :users, :controllers => {:registrations => "registrations"}

  get '/admin/pays' => 'countries#index_admin', as: :country_admin_index
  get '/admin/pays/new' => 'countries#new', as: :country_new
  post '/admin/pays/create' => 'countries#create', as: :country_create
  patch '/admin/pays/update/:id' => 'countries#update', as: :country_update
  get '/admin/pays/edit/:id' => 'countries#edit', as: :country_edit
  delete '/admin/pays/delete/:id' => 'countries#destroy', as: :country_delete

  get '/admin/utilisateurs' => 'admin#users_index', as: :users_admin_index
  get '/admin/utilisateurs/download' => 'admin#users_download', as: :users_download

  get '/admin/matches' => 'match#index_admin', as: :match_admin
  get '/admin/match/new' => 'match#new', as: :match_new
  get '/matchs/' => 'match#index', as: :match
  post '/admin/match/create' => 'match#create', as: :match_create
  delete '/admin/match/delete/:id' => 'match#destroy', as: :match_delete
  get '/admin/match/edit/:id' => 'match#edit', as: :match_edit
  put '/admin/match/update/:id' => 'match#update', as: :match_update

  get '/admin/pools' => 'pool#index_admin', as: :pools_admin
  get '/admin/pool/new' => 'pool#new', as: :pool_new
  post '/admin/pool/create' => 'pool#create', as: :pool_create
  delete '/admin/pool/delete/:id' => 'pool#destroy', as: :pool_delete
  get '/admin/pool/edit/:id' => 'pool#edit', as: :pool_edit
  put '/admin/pool/update/:id' => 'pool#update', as: :pool_update

  get '/results' => 'results#resultats'

  get '/admin/stades' => 'stade#index_admin', as: :stade_admin
  get '/admin/stade/new' => 'stade#new', as: :stade_new
  post 'admin/stade/create' => 'stade#create', as: :stade_create
  delete '/admin/stade/delete/:id' => 'stade#destroy', as: :stade_delete
  get '/admin/stade/edit/:id' => 'stade#edit', as: :stade_edit
  put '/admin/stade/update/:id' => 'stade#update', as: :stade_update

  get '/admin/prizes' => 'prizes#index_admin', as: :prize_admin_index
  get '/admin/prizes/new' => 'prizes#new', as: :prize_new
  get '/prizes/' => 'prizes#index', as: :prize
  post '/admin/prizes/create' => 'prizes#create', as: :prize_create
  patch '/admin/prizes/update/:id' => 'prizes#update', as: :prize_update
  get '/admin/prizes/edit/:id' => 'prizes#edit', as: :prize_edit
  delete '/admin/prizes/delete/:id' => 'prizes#destroy', as: :prize_delete

  get '/legales/sitemap' => 'legales#sitemap', as: :sitemap
  get '/legales/reglement' => 'legales#rules', as: :rules

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :local_matches, class_name: 'Match', foreign_key: :first_country_id
  has_many :remote_matches, class_name: 'Match', foreign_key: :second_country_id
  has_attached_file :image
  validates_attachment :image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }, styles: { thumb: ["300x100#"] }
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!, :admin_require

  def index_admin
    @countries = Country.order(:name => :asc).paginate(:page => params[:page]);
  end

  def create
    @country = Country.new(country_params)

    @country.save
    redirect_to :country_admin_index
  end

  def new

  end

  def edit
    @country = Country.find(params[:id])
  end

  def update
    @country = Country.find(params[:id])

    if @country.update(country_params)
      redirect_to :country_admin_index
    else
      render 'edit'
    end
  end

  def destroy
    @country = Country.find(params[:id])
    @country.destroy

    redirect_to :country_admin_index
  end

  private
  def country_params
    params.require(:country).permit(:name, :description, :image)
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/edit.html.erb
<% content_for :header do %>
    <h2>Modifier "<%= @country.name %>"</h2>
<% end %>

<div class="col-xs-6">
  <div class="box box-primary">
    <%= form_for :country, url: country_update_path(@country), method: :patch do |f| %>
        <div class="box-body">
          <div class="form-group">
            <label>Nom du pays</label>
            <%= f.text_field :name, class: 'form-control', placeholder: 'Entrez le nom du pays' %>
            <label>Description du pays</label>
            <%= f.text_field :description, class: 'form-control', placeholder: 'Entrez une description du pays' %>
            <%= f.label :image %>
            <%= f.file_field :image, class: 'form-control'%>
          </div>
        </div>

        <div class="box-footer">
          <%= f.submit value: 'Enregistrer', class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>

app/views/countries/index_admin.html.erb
<% content_for 'header' do %>
  <h2>Listes des pays existants</h2>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Hover Data Table</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
            <div class="row">
              <div class="col-sm-6"></div>
              <div class="col-sm-6"></div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                  <col width="auto">
                  <col width="100px">
                  <thead>
                    <tr role="row">
                      <th class="sorting" tabindex="0" rowspan="1" colspan="1">Pays</th>
                      <th class="middle-desc" rowspan="1" colspan="1">Description</th>
                      <th class="" rowspan="1" colspan="1">Flag</th>
                      <th class="actions-row" rowspan="1" colspan="1">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @countries.each do |country| %>
                      <tr role="row" class="odd">
                        <td><%= country.name %></td>
                        <td><%= country.description %></td>
                        <td><%= image_tag(country.image.url, :class => "flag")%></td>
                        <td>
                          <%= link_to country_edit_path(country), data: {no_turbolink: true} do %>
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                          <% end %>

                          <%= link_to country_delete_path(country), method: :delete, data: { confirm: 'Are you sure?' } do %>
                            <span class="glyphicon glyphicon-remove-circle red" aria-hidden="true"></span>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                  <tfoot>
                    <tr>
                      <th rowspan="1" colspan="1">Pays</th>
                      <th class="middle-desc" rowspan="1" colspan="1">Description</th>
                      <th class="" rowspan="1" colspan="1">Flag</th>
                      <th class="actions-row" rowspan="1" colspan="1">Actions</th>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-5">
              <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">
                Showing <%= @countries.current_page %> to <%= @countries.total_pages %> of <%= @countries.count %> entries
              </div>
            </div>
            <div class="col-sm-7">
              <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                <%= will_paginate(@countries, :renderer => AdminHelper::LinkRenderer) %>
              </div>
            </div>
          </div>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    </div><!-- /.col -->
  </div><!-- /.row -->

  <%= link_to 'Ajouter un pays', country_new_path, class: 'btn btn-primary' %>
</section>

app/views/countries/new.html.erb
<% content_for :header do %>
  <h2>Ajouter un nouveau pays</h2>
<% end %>

<div class="col-xs-6">
  <div class="box box-primary">
    <%= form_for :country, url: country_create_path do |f| %>

      <div class="box-body">
        <div class="form-group">
          <label>Nom du pays</label>
          <%= f.text_field :name, class: 'form-control', placeholder: 'Entrez le nom du pays' %>
          <label>Description du pays</label>
          <%= f.text_field :description, class: 'form-control', placeholder: 'Entrez une description du pays' %>
          <%= f.label :image %>
          <%= f.file_field :image, class: 'form-control'%>
        </div>
      </div>

      <div class="box-footer">
        <%= f.submit value: 'Enregistrer', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>