config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/admin' => 'admin#index', as: :admin_index

  devise_for :users, :controllers => {:registrations => "registrations"}

  get '/admin/pays' => 'countries#index_admin', as: :country_admin_index
  get '/admin/pays/new' => 'countries#new', as: :country_new
  post '/admin/pays/create' => 'countries#create', as: :country_create
  patch '/admin/pays/update/:id' => 'countries#update', as: :country_update
  get '/admin/pays/edit/:id' => 'countries#edit', as: :country_edit
  delete '/admin/pays/delete/:id' => 'countries#destroy', as: :country_delete

  get '/admin/utilisateurs' => 'admin#users_index', as: :users_admin_index
  get '/admin/utilisateurs/download' => 'admin#users_download', as: :users_download

  get '/admin/matches' => 'match#index_admin', as: :match_admin
  get '/admin/match/new' => 'match#new', as: :match_new
  get '/matchs/' => 'match#index', as: :match
  post '/admin/match/create' => 'match#create', as: :match_create
  delete '/admin/match/delete/:id' => 'match#destroy', as: :match_delete
  get '/admin/match/edit/:id' => 'match#edit', as: :match_edit
  put '/admin/match/update/:id' => 'match#update', as: :match_update

  get '/admin/pools' => 'pool#index_admin', as: :pools_admin
  get '/admin/pool/new' => 'pool#new', as: :pool_new
  post '/admin/pool/create' => 'pool#create', as: :pool_create
  delete '/admin/pool/delete/:id' => 'pool#destroy', as: :pool_delete
  get '/admin/pool/edit/:id' => 'pool#edit', as: :pool_edit
  put '/admin/pool/update/:id' => 'pool#update', as: :pool_update

  get '/results' => 'results#resultats'

  get '/admin/stades' => 'stade#index_admin', as: :stade_admin
  get '/admin/stade/new' => 'stade#new', as: :stade_new
  post 'admin/stade/create' => 'stade#create', as: :stade_create
  delete '/admin/stade/delete/:id' => 'stade#destroy', as: :stade_delete
  get '/admin/stade/edit/:id' => 'stade#edit', as: :stade_edit
  put '/admin/stade/update/:id' => 'stade#update', as: :stade_update

  get '/admin/prizes' => 'prizes#index_admin', as: :prize_admin_index
  get '/admin/prizes/new' => 'prizes#new', as: :prize_new
  get '/prizes/' => 'prizes#index', as: :prize
  post '/admin/prizes/create' => 'prizes#create', as: :prize_create
  patch '/admin/prizes/update/:id' => 'prizes#update', as: :prize_update
  get '/admin/prizes/edit/:id' => 'prizes#edit', as: :prize_edit
  delete '/admin/prizes/delete/:id' => 'prizes#destroy', as: :prize_delete

  get '/legales/sitemap' => 'legales#sitemap', as: :sitemap
  get '/legales/reglement' => 'legales#rules', as: :rules

end

app/controllers/prizes_controller.rb
class PrizesController < ApplicationController
  layout 'admin', except: [:index]
  before_action :authenticate_user!, :admin_require, except: [:index]

  def index_admin
    @prizes = Prize.order(:name => :asc)
  end

  def create
    @prize = Prize.new(prize_params)

    @prize.save
    redirect_to :prize_admin_index
  end

  def new

  end

  def edit
    @prize = Prize.find(params[:id])
  end

  def update
    @prize = Prize.find(params[:id])

    if @prize.update(prize_params)
      redirect_to :prize_admin_index
    else
      render 'edit'
    end
  end

  def destroy
    @prize = Prize.find(params[:id])
    @prize.destroy

    redirect_to :prize_admin_index
  end

  def index
    @prizes = Prize.order(name: :asc)
  end

  private
  def prize_params
    params.require(:prize).permit(:name, :description, :quantity, :ref, :image)
  end
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/views/prizes/edit.html.erb
<% content_for :header do %>
    <h2>Modifier "<%= @prize.name %>"</h2>
<% end %>

<div class="col-xs-6">
  <div class="box box-primary">
    <%= form_for :prize, url: prize_update_path(@prize), method: :patch do |f| %>
        <div class="box-body">
          <div class="form-group">
            <label>Nom du lot</label>
            <%= f.text_field :name, class: 'form-control', placeholder: 'Entrez le nom du lot' %>
            <label>Description du lot</label>
            <%= f.text_field :description, class: 'form-control', placeholder: 'Entrez une description du lot' %>
            <label>Quantité</label>
            <%= f.text_field :quantity, class: 'form-control' %>
            <label>Rérérence</label>
            <%= f.text_field :ref, class: 'form-control' %>

            <%= f.label :image %>
            <%= f.file_field :image, class: 'form-control'%>
          </div>
        </div>

        <div class="box-footer">
          <%= f.submit value: 'Enregistrer', class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>

app/views/prizes/index.html.erb
<section class="prizes-section">
  <div class="filter-prizes">
    <div class="container">
      <div class="title-prizes col-lg-12"> 
        <h1>Tous les LOTS</h1> 
      </div>

      <div class="row prizes-content">
      <% @prizes.each do |prize| %>
        <div class="prize-encart">
          <div class="first-part">
            <%= image_tag(prize.image.url, :class => "")%>
          </div>
          <div class="second-part">
            <h3><%= prize.name %></h3>
            <p><%= prize.description %></p>
          </div>
        </div>
      <% end %>
      <div class="clear"></div>
      </div>
    </div>
  </div>
</section>

app/views/prizes/index_admin.html.erb
<% content_for 'header' do %>
    <h2>Listes des pays existants</h2>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Hover Data Table</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
            <div class="row">
              <div class="col-sm-6"></div>
              <div class="col-sm-6"></div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                  <col width="auto">
                  <col width="100px">
                  <thead>
                  <tr role="row">
                    <th class="sorting" tabindex="0" rowspan="1" colspan="1">Nom du lot</th>
                    <th class="" rowspan="1" colspan="1">Description</th>
                    <th class="" rowspan="1" colspan="1">Quantité</th>
                    <th class="" rowspan="1" colspan="1">Référence</th>
                    <th class="" rowspan="1" colspan="1">Image</th>
                    <th class="actions-row" rowspan="1" colspan="1">Actions</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @prizes.each do |prize| %>
                      <tr role="row" class="odd">
                        <td><%= prize.name %></td>
                        <td><%= prize.description %></td>
                        <td><%= prize.quantity %></td>
                        <td><%= prize.ref %></td>
                        <td><%= image_tag(prize.image.url, :class => "flag")%></td>
                        <td>
                          <%= link_to prize_edit_path(prize), data: {no_turbolink: true} do %>
                              <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                          <% end %>

                          <%= link_to prize_delete_path(prize), method: :delete, data: { confirm: 'Are you sure?' } do %>
                              <span class="glyphicon glyphicon-remove-circle red" aria-hidden="true"></span>
                          <% end %>
                        </td>
                      </tr>
                  <% end %>
                  </tbody>
                  <tfoot>
                  <tr>
                    <th class="sorting" tabindex="0" rowspan="1" colspan="1">Nom du lot</th>
                    <th class="" rowspan="1" colspan="1">Description</th>
                    <th class="" rowspan="1" colspan="1">Quantité</th>
                    <th class="" rowspan="1" colspan="1">Référence</th>
                    <th class="" rowspan="1" colspan="1">Image</th>
                    <th class="actions-row" rowspan="1" colspan="1">Actions</th>
                  </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-5">
              <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">

              </div>
            </div>
            <div class="col-sm-7">
              <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">

              </div>
            </div>
          </div>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    </div><!-- /.col -->
  </div><!-- /.row -->

  <%= link_to 'Ajouter un Lot', prize_new_path, class: 'btn btn-primary' %>
</section>

app/views/prizes/new.html.erb
<% content_for :header do %>
    <h2>Ajouter un nouveau lot</h2>
<% end %>

<div class="col-xs-6">
  <div class="box box-primary">
    <%= form_for :prize, url: prize_create_path do |f| %>
        <div class="box-body">
          <div class="form-group">
            <label>Nom du lot</label>
            <%= f.text_field :name, class: 'form-control', placeholder: 'Entrez le nom du lot' %>
            <label>Description du lot</label>
            <%= f.text_field :description, class: 'form-control', placeholder: 'Entrez une description du lot' %>
            <label>Quantité</label>
            <%= f.text_field :quantity, class: 'form-control' %>
            <label>Rérérence</label>
            <%= f.text_field :ref, class: 'form-control' %>

            <%= f.label :image %>
            <%= f.file_field :image, class: 'form-control'%>
          </div>
        </div>

        <div class="box-footer">
          <%= f.submit value: 'Enregistrer', class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>